apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: ksqldb-cluster-ksqlcluster
  namespace: confluent
spec:
  clustersScopeByIds:
    ksqlClusterId: confluent.ksqldb_
  principal:
    name: ksql
    type: user
  resourcePatterns:
    - name: ksql-cluster
      patternType: LITERAL
      resourceType: KsqlCluster
  role: ResourceOwner
---
