apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: ksqldb-cluster-groups
  namespace: confluent
spec:
  principal:
    name: ksql
    type: user
  resourcePatterns:
    - name: _confluent-ksql-ksqldb-cluster
      patternType: PREFIXED
      resourceType: Group
  role: ResourceOwner
