apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: confluent
  namespace: sandbox
spec:
  interval: 1m
  chart:
    spec:
      chart: confluent-for-kubernetes
      sourceRef:
        name: confluent-for-kubernetes
        kind: HelmRepository
        namespace: flux-system
  values:
    image:
      registry: docker.io
    name: confluent-operator-global