apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - proxy.yaml
  - ldap.yaml
#  - confluent-operator-credentials.yaml
#  - confluent-operator-helm-release-dev.yaml
#  - confluent-operator-helm-release-production.yaml
#  - confluent-operator-helm-release-confluent.yaml