---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dev
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: core
  path: ./apps/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: confluent
  validation: client