---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 1m
  path: ./infrastructure
  prune: false
  sourceRef:
    kind: GitRepository
    name: confluent
    namespace: flux-system