apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: environments
  namespace: flux-system
spec:
  dependsOn:
    - name: shared
  interval: 5m
  path: "./environments"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system