---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
spec:
  dependencies:
    zookeeper:
      endpoint: zookeeper.production.svc.cluster.local:2182
  metricReporter:
    bootstrapEndpoint: kafka.production.svc.cluster.local:9071
