apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: admin-groups-kafka-cluster-connect
  namespace: confluent
spec:
  clustersScopeByIds:
    connectClusterId: confluent.connect
  principal:
    name: admins
    type: group
  resourcePatterns:
    - name: "*"
      resourceType: Connector
  role: ResourceOwner
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: admin-groups-kafka-cluster-sr
  namespace: confluent
spec:
  clustersScopeByIds:
    schemaRegistryClusterId: schema-registry
  principal:
    name: admins
    type: group
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: admin-groups-kafka-cluster-ksql
  namespace: confluent
spec:
  clustersScopeByIds:
    ksqlClusterId: ksqldb-cluster
  principal:
    name: admins
    type: group
  role: SystemAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: admin-group-topics
  namespace: confluent
spec:
  principal:
    name: admins
    type: group
  resourcePatterns:
    - name: "*"
      resourceType: Topic
  role: ResourceOwner
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: admin-group-groups
  namespace: confluent
spec:
  principal:
    name: admins
    type: group
  resourcePatterns:
    - name: "*"
      resourceType: Group
  role: ResourceOwner
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: admin-group-transactionalid
  namespace: confluent
spec:
  principal:
    name: admins
    type: group
  resourcePatterns:
    - name: "*"
      resourceType: TransactionalId
  role: ResourceOwner