apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: confluent-private
  namespace: flux-system
spec:
  url: https://confluent.jfrog.io/confluent/helm-early-access-operator-2
  secretRef:
    name: https-credentials
  interval: 1m
