apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: connect-cluster-base
  namespace: confluent
spec:
  clustersScopeByIds:
    connectClusterId: confluent.connect
  principal:
    name: connect
    type: user
  role: SecurityAdmin
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: connect-resources-base
  namespace: confluent
spec:
  principal:
    name: connect
    type: user
  resourcePatterns:
    - name: confluent.connect
      patternType: LITERAL
      resourceType: Group
    - name: confluent.connect-
      patternType: PREFIXED
      resourceType: Topic
  role: ResourceOwner
---
apiVersion: platform.confluent.io/v1beta1
kind: ConfluentRolebinding
metadata:
  name: connect-monitoring-base
  namespace: confluent
spec:
  principal:
    name: connect
    type: user
  resourcePatterns:
    - name: _confluent-monitoring
      patternType: PREFIXED
      resourceType: Topic
  role: DeveloperWrite


