---
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
spec:
  tls:
    enabled: true
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.sandbox.svc.cluster.local:9071
      tls:
        enabled: true

